#!/bin/bash

#SBATCH --time=20:00:00
#SBATCH --cpus-per-task=6
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=2GB
#SBATCH --job-name=Mario_Long_test_run
#SBATCH --output=job-%j.log
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1


module load Python/3.10.4-GCCcore-11.3.0

which python

source $HOME/Desktop/Mario/Venv/v/bin/activate


python3 --version
python -u $HOME/Desktop/Mario/Files/A3C/train.py

deactivate